// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: `prisma/schema.prisma`,
  migrations: {
    path: `prisma/migrations`,
  },
  datasource: {
    url: "postgresql://neondb_owner:npg_2I7dJjqLDYxp@ep-muddy-glitter-a1008ghv-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
    provider: "postgresql"
  }
});
